INSERT INTO District (DistrictName) VALUES
('Bengaluru City'),
('Bengaluru Rural'),
('Mysuru'),
('Mangaluru'),
('Hubballi-Dharwad'),
('Belagavi'),
('Kalaburagi'),
('Ballari'),
('Vijayapura'),
('Tumakuru'),
('Shivamogga'),
('Udupi'),
('Davanagere'),
('Raichur'),
('Hassan'),
('Mandya'),
('Chikkamagaluru'),
('Kodagu'),
('Bidar'),
('Kolar'),
('Bagalkote'),
('Chamarajanagara'),
('Chikkaballapura'),
('Chitradurga'),
('Gadag'),
('Haveri'),
('Koppal'),
('Ramanagara'),
('Uttara Kannada'),
('Yadgir'),
('Vijayanagara');